---
spring: 
  profiles: 
    active: local
mybatis: 
  configuration: 
    map-underscore-to-camel-case: true
---
spring: 
  profiles: local
  datasource: 
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test?serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 1234
...
